Repository junit-pioneer/junit-pioneer, pull requests merged in 2022-09, with the labels that each got.

#667 Add issues templates for feature requests and bug reports (#589 / #667)
  .github/feature_request.md
  .github/issue--bug-report.md
  CONTRIBUTING.md
Labels: 🚦 status: ready

#666 Improve Cartesian test documentation
  docs/cartesian-product.adoc
  src/demo/java/org/junitpioneer/jupiter/cartesian/CartesianTestExtensionDemo.java
  src/main/java/org/junitpioneer/jupiter/cartesian/CartesianEnumArgumentsProvider.java
  src/test/java/org/junitpioneer/jupiter/cartesian/CartesianTestExtensionTests.java
Labels: merge-ready

#635 Removing CartesionProductExtension version 1 (#517 / #635)
  docs/cartesian-product-v1.adoc
  docs/cartesian-product.adoc
  src/main/java/org/junitpioneer/jupiter/CartesianAnnotationConsumer.java
  src/main/java/org/junitpioneer/jupiter/CartesianEnumArgumentsProvider.java
  src/main/java/org/junitpioneer/jupiter/CartesianEnumSource.java
  src/main/java/org/junitpioneer/jupiter/CartesianProductResolver.java
  src/main/java/org/junitpioneer/jupiter/CartesianProductTest.java
  src/main/java/org/junitpioneer/jupiter/CartesianProductTestExtension.java
  src/main/java/org/junitpioneer/jupiter/CartesianProductTestInvocationContext.java
  src/main/java/org/junitpioneer/jupiter/CartesianValueArgumentsProvider.java
  src/main/java/org/junitpioneer/jupiter/CartesianValueSource.java
  src/main/java/org/junitpioneer/jupiter/NullEnum.java
  src/main/java/org/junitpioneer/jupiter/package-info.java
  src/main/java/org/junitpioneer/jupiter/params/ByteRangeSource.java
  src/main/java/org/junitpioneer/jupiter/params/DoubleRangeSource.java
  src/main/java/org/junitpioneer/jupiter/params/FloatRangeSource.java
  src/main/java/org/junitpioneer/jupiter/params/IntRangeSource.java
  src/main/java/org/junitpioneer/jupiter/params/LongRangeSource.java
  src/main/java/org/junitpioneer/jupiter/params/RangeSourceArgumentsProvider.java
  src/main/java/org/junitpioneer/jupiter/params/ShortRangeSource.java
  src/test/java/org/junitpioneer/jupiter/CartesianProductTestExtensionTests.java
Labels: merge-ready, 🚦 status: ready

#662 Replace Locale constructor by Locale builder (#658 / #662)
  docs/default-locale-timezone.adoc
  src/demo/java/org/junitpioneer/jupiter/DefaultLocaleTimezoneExtensionDemo.java
  src/main/java/org/junitpioneer/internal/PioneerUtils.java
  src/main/java/org/junitpioneer/jupiter/DefaultLocale.java
  src/main/java/org/junitpioneer/jupiter/DefaultLocaleExtension.java
  src/test/java/org/junitpioneer/jupiter/DefaultLocaleTests.java
Labels: merge-ready, 🚦 status: ready

#627 Update Java version to 11 Part 1 (#617 / #627)
  .github/workflows/build.yml
  README.md
  build.gradle.kts
  gradle.properties
  src/main/java/module-info.java
  src/test/java/module-info.java
Labels: merge-ready, 🚦 status: ready

#664 Fix JSON sources to convert to Lists and other types
  docs/json-argument-source.adoc
  src/demo/java/org/junitpioneer/jupiter/json/JsonArgumentSourceExtensionDemo.java
  src/main/java/org/junitpioneer/jupiter/json/AbstractJsonArgumentsProvider.java
  src/main/java/org/junitpioneer/jupiter/json/JacksonNode.java
  src/main/java/org/junitpioneer/jupiter/json/Node.java
  src/test/java/org/junitpioneer/jupiter/json/ArrayNodeToListTests.java
  src/test/resources/org/junitpioneer/jupiter/json/bad_poems.json
  src/test/resources/org/junitpioneer/jupiter/json/composers.json
  src/test/resources/org/junitpioneer/jupiter/json/poets.json
Labels: merge-ready

#674 Remove branch filtering from build
  .github/workflows/build.yml
Labels: merge-ready
